name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: copy to aliyun
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: 101.200.238.139
          user: root
          pass: Xzd20021224

          # 由于网路情况，很容易超时，设置为60s
          connect_timeout: 60s

          # 将工作目录下的文件全部拷贝到部署服务器的工作目录
          scp: |
            ./* => /projectTest/Myp
          last_ssh: |
            cd /projectTest/Myp
            docker stop Myp
            docker rm Myp
            docker build -t next-new .
            docker run -d -p 3000:3000 --name Myp next-new
